{
 "title": "vgsales-db",
 "time": { "from": "1959-12-31T11:00:00.500Z", "to": "2040-01-02T10:59:58.500Z" },
 "panels": [
  {
   "title": "Regions based stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nombre de ventes de jeux vidéos par genre en Europe",
     "type": "graph",
     "description": "par type et par année, avec des sous totaux par : Type, Année, Type et année, total général ",
     "gridPos": { "h": 8, "w": 19, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "currencyUSD", "label": "Revenus" }
     ],
     "targets": [
      {
       "rawSql": "SELECT G.genre as genre, G.release_year as time, sum(F.eu_sales) as metric\nFROM Game G, Fact F\nWHERE G.game_id = F.game_id\nGROUP BY CUBE (G.genre, G.release_year)\nORDER BY metric DESC"
      }
     ]
    },
    {
     "title": "Nombre de ventes de jeux vidéos par genre en Europe",
     "type": "table",
     "description": "par type et par année, avec des sous totaux par : Type, Année, Type et année, total général ",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT G.genre as genre, G.release_year as time, sum(F.eu_sales) as metric\nFROM Game G, Fact F\nWHERE G.game_id = F.game_id\nGROUP BY CUBE (G.genre, G.release_year)\nORDER BY metric DESC"
      }
     ]
    }
   ]
  },
  {
   "title": "Publishers and Developers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Les publishers les plus réussis en 2010",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "-- En une année spécifique\nSELECT p.publisher_name as series, SUM(f.na_sales) as na_sales, SUM(f.jp_sales) as jp_sales, SUM(f.eu_sales) eu_sales, SUM(f.other_sales) as other_sales, SUM(f.global_sales) as global_sales\nFROM Publisher p, Fact f, Game g\nWHERE p.publisher_id = f.publisher_id AND f.game_id = g.game_id AND extract(YEAR FROM g.release_year) = 2010\nGROUP BY ROLLUP (p.publisher_name)\nORDER BY global_sales DESC\nLIMIT 10\n"
      }
     ]
    },
    {
     "title": "Les publishers les plus réussis en 2010 de tous les temps",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "rawSql": "-- Tous les temps\nSELECT p.publisher_name, SUM(f.na_sales) as na_sales, SUM(f.jp_sales) as jp_sales, SUM(f.eu_sales) eu_sales, SUM(f.other_sales) as other_sales, SUM(f.global_sales) as global_sales\nFROM Publisher p, Fact f\nWHERE p.publisher_id = f.publisher_id\nGROUP BY ROLLUP (p.publisher_name)\nORDER BY global_sales DESC\nLIMIT 10"
      }
     ]
    },
    {
     "title": "Breakdown des revenus de Activision (Publisher) par ses studios en 2010",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "-- En 2010\nSELECT p.publisher_name, d.developer_name, SUM(f.global_sales) as global_sales\nFROM Publisher p, Fact f, Developer d, Game g\nWHERE p.publisher_id = f.publisher_id AND f.developer_id = d.developer_id \n\tAND f.game_id = g.game_id \n      AND extract(year from g.release_year) = 2010 -- Supp pour tous les temps\n\tAND p.publisher_name = 'Activision'\nGROUP BY ROLLUP (p.publisher_name, d.developer_name)\nORDER BY global_sales DESC"
      }
     ]
    },
    {
     "title": "Breakdown des revenus de Ubisoft (Developer) par ses produits en 2010?",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
     "targets": [
      {
       "rawSql": "\n\nSELECT d.developer_name, g.title, SUM(f.global_sales) as global_sales\nFROM Fact f, Developer d, Game g\nWHERE f.developer_id = d.developer_id\n\tAND f.game_id = g.game_id \n\tAND extract(year from g.release_year) = 2010\n\tAND lower(d.developer_name) = 'ubisoft'\nGROUP BY ROLLUP (d.developer_name, g.title)\nORDER BY global_sales DESC"
      }
     ]
    },
    {
     "title": "Les genres qui génèrent le plus de revenu pour les 10 meilleurs développeur en 2010",
     "type": "table",
     "description": "Les genres qui génèrent le plus de revenu pour les 10 meilleurs développeur en 2010",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
     "targets": [
      {
       "rawSql": "WITH game_sales_per_genre AS (\n\tSELECT g.genre, d.developer_name, f.global_sales\n\tFROM Fact f, Developer d, Game g\n\tWHERE f.developer_id = d.developer_id\n\t\tAND f.game_id = g.game_id \n\t\tAND extract(year from g.release_year) = 2010\n\tORDER BY f.global_sales DESC\n\tLIMIT 10\n) \tSELECT genre, developer_name, SUM(global_sales) as global_sales\n\tFROM game_sales_per_genre\n\tGROUP BY CUBE(genre, developer_name)\n\tORDER BY genre"
      }
     ]
    },
    {
     "title": "Breakdown des revenus de Ubisoft (Developer) par les genres de jeux-vidéo en 2010",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT d.developer_name, g.genre, SUM(f.global_sales) as global_sales\nFROM Fact f, Developer d, Game g\nWHERE f.developer_id = d.developer_id\n\tAND f.game_id = g.game_id \n\tAND extract(year from g.release_year) = 2010\n\tAND lower(d.developer_name) = 'ubisoft'\nGROUP BY ROLLUP (d.developer_name, g.genre)\nORDER BY global_sales DESC"
      }
     ]
    }
   ]
  },
  {
   "title": "Platforms and Critics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Les meilleurs jeux selon les critiques et les joueurs",
     "type": "table",
     "description": "Les meilleurs jeux selon les critiques et les joueurs",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT G.title, P.platform_name, TRUNC(AVG(F.critic_score),2) AS critics, TRUNC(AVG(F.user_score),2) AS users\nFROM Fact F, Game G, platform P\nWHERE F.game_id = G.game_id\n      AND F.platform_id = P.platform_id\n      AND F.critic_score IS NOT NULL\n      AND F.user_score IS NOT NULL\nGROUP BY (G.title,P.platform_name)"
      }
     ]
    },
    {
     "title": "Les nombres de ventes par plateforme",
     "type": "table",
     "gridPos": { "h": 20, "w": 6, "x": 12, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT P.platform_name, SUM(F.Global_sales) as global_sales\nFROM Platform P, Fact F\nWHERE P.platform_id = F.platform_id\nGROUP BY ROLLUP(P.platform_name)\nOrder by SUM(F.Global_sales) DESC"
      }
     ]
    },
    {
     "title": "Plateforme qui a sorti les meilleurs jeux",
     "type": "table",
     "gridPos": { "h": 20, "w": 6, "x": 18, "y": 3 },
     "targets": [
      {
       "rawSql": "WITH platform_rank AS (\n  SELECT P.platform_name as platform_name, TRUNC(AVG(F.critic_score),2) AS score\n  FROM Fact F, Game G, platform P\n  WHERE F.game_id = G.game_id\n  AND F.platform_id = P.platform_id\n  AND F.critic_score IS NOT NULL\n  GROUP BY P.platform_name \n) SELECT platform_name, score, rank() OVER (ORDER BY score DESC) rank_number \n\tFROM platform_rank"
      }
     ]
    },
    {
     "title": "Les jeux les plus vendus pour chacune des plateformes",
     "type": "table",
     "gridPos": { "h": 16, "w": 6, "x": 0, "y": 13 },
     "targets": [
      {
       "rawSql": "SELECT P.platform_name, G.title, F.global_sales\nFROM Platform P, Game G, Fact F\nWHERE F.game_id = G.game_id\nAND F.platform_id = P.platform_id\nAND F.global_sales = (SELECT MAX(F.global_sales) \n                      FROM Fact F \n                      WHERE F.platform_id = P.platform_id)\nGROUP BY P.platform_name, G.title, F.global_sales\nORDER BY F.global_sales DESC\n"
      }
     ]
    },
    {
     "title": "Moyenne des critiques par Publisher, par Developer, et par binôme Developer/Publisher",
     "type": "table",
     "gridPos": { "h": 16, "w": 6, "x": 6, "y": 13 },
     "targets": [
      {
       "rawSql": "SELECT P.publisher_name, D.developer_name, AVG(F.critic_score) as score\nFROM Publisher P, Fact F, Developer D\nWHERE P.publisher_id = F.publisher_id AND D.developer_id = F.developer_id and F.critic_score >= 0\nGROUP BY GROUPING SETS(P.publisher_name, D.developer_name, (P.publisher_name, D.developer_name))\nORDER BY score DESC"
      }
     ]
    }
   ]
  }
 ]
}